### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by lalma** [lalma/RacoonOlyLarvalSurvival#4]
https://github.com/lalma/RacoonOlyLarvalSurvival/blob/4df9dffa1a7185bedc4512b248da7a2a494b7fc8/R/RaccoonLikelyhoodLarvaeInJar.R#L108-L110

Warning messages:
1: Unknown or uninitialised column: `treatment`. 
2: Unknown or uninitialised column: `jar_id`. 
3: Unknown or uninitialised column: `site`. 
4: Unknown or uninitialised column: `treatment`. 
5: Unknown or uninitialised column: `jar_id`. 
6: Unknown or uninitialised column: `site`

**Comment by pmcelhany** [comment]
I don't get these warnings. This code has noe been changes so does not include the call to unite. Does this still happen now?

**Comment by lalma** [comment]
not sure what was happening, but I dont get this error any more
